### ISSUE TITLE
relude-0.6.0.0 fails its test suite

### ISSUE THREAD

**Issue by peti** [kowainik/relude#241] opened 2020-01-31 12:50 UTC
Building on Linux with ghc-8.8.1 I got:

~~~
Running 2 test suites...
Test suite relude-doctest: RUNNING...
src/Relude/DeepSeq.hs:36: failure in expression `:sprint list'
expected: list = _
 but got: list = [2,1,3]

src/Relude/DeepSeq.hs:50: failure in expression `:sprint list'
expected: list = _
 but got: list = [2,1,3]

src/Relude/DeepSeq.hs:65: failure in expression `:sprint list'
expected: list = _
 but got: list = [2,1,3]

src/Relude/DeepSeq.hs:81: failure in expression `:sprint list'
expected: list = _
 but got: list = [2,1,3]

Examples: 445  Tried: 437  Errors: 0  Failures: 4
Test suite relude-doctest: FAIL
Test suite logged to: dist/test/relude-0.6.0.0-relude-doctest.log
Test suite relude-test: RUNNING...
Test suite relude-test: PASS
Test suite logged to: dist/test/relude-0.6.0.0-relude-test.log
1 of 2 test suites (1 of 2 test cases) passed.
~~~

**Comment by chshersh** [comment] 2020-02-03 16:47
@peti thanks for reporting the issue. This is a known problem and is caused by changes in GHC; I opened the following ticket there a while ago:

* https://gitlab.haskell.org/ghc/ghc/issues/17422

The fix for tests is already implemented in the following commit:

* https://github.com/kowainik/relude/commit/bfb5f60dd41bd3e3a25ec222ce338f302f1f513e

Unfortunately, it didn't get into `0.6.0.0` release despite thorough checks on CI for multiple GHC versions. However, if you build from `master`, you shouldn't get this error.

**Comment by vrom911** [comment] 2020-03-25 18:29
Unfortunately, we can't do anything to `0.6.0.0`, but this is already fixed in master, so it is going to be in the `0.7.0.0` release :slightly_smiling_face:

**Closed by vrom911** 2020-03-25 18:29 UTC
Labels: question, tests
